### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by henrykironde** [weecology/retriever.jl#44]
Since the docs are not auto deploying, we need to build them manually and update them.

**Comment by henrykironde** [comment]
Additionally, we shall need to bump up the version for the dev. I want to think that changing the version number [here](https://github.com/weecology/Retriever.jl/blob/master/Project.toml#L13) is all we need.

**Comment by ethanwhite** [comment]
I updated the docs manually, but I'm not sure it worked properly. All functions are now in the form `Main.Retriever.check_for_updates` instead of `Retriever.check_for_updates` (like it was in previous versions):

https://weecology.github.io/Retriever.jl/latest/

Is that correct or did I do something wrong when building the docs?

**Comment by henrykironde** [comment]
That is fine, the doc strings format changed. Thank you so much @ethanwhite
